version: '3.1'

services:
  server-bootstrap:
    image: consul:latest
    hostname: "consul.server"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "consul agent -config-file /consul/config/config.json"
    networks:
      - traefik_traefik
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - /opt/consul:/consul/config
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.consul.rule=Host(`consul.project.lambla.eu`)"
        - "traefik.http.routers.consul.entrypoints=web"
        - "traefik.http.services.consul.loadbalancer.server.port=8500"

networks:
  traefik_traefik:
    driver: overlay
    external: true
